Name:           ros-kinetic-thormang3-action-editor
Version:        0.1.1
Release:        0%{?dist}
Summary:        ROS thormang3_action_editor package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/thormang3_action_editor
Source0:        %{name}-%{version}.tar.gz

Requires:       ncurses-devel
Requires:       ros-kinetic-robotis-controller
Requires:       ros-kinetic-robotis-controller-msgs
Requires:       ros-kinetic-robotis-framework-common
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-thormang3-action-module
BuildRequires:  ncurses-devel
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-robotis-controller
BuildRequires:  ros-kinetic-robotis-controller-msgs
BuildRequires:  ros-kinetic-robotis-framework-common
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-std-msgs
BuildRequires:  ros-kinetic-thormang3-action-module

%description
The thormang3_action_editor package This package is a action editor for
thormang3. The action file which is edited by this editor will be used with this
action editor.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Tue Apr 25 2017 Pyo <pyo@robotis.com> - 0.1.1-0
- Autogenerated by Bloom

